set -g default-terminal "tmux-256color"
set -as terminal-overrides ',*:RGB'
if-shell -b '[ "$(printf "%s\n3.3" "$(tmux -V | cut -d" " -f2)" | sort -V | head -n1)" = "3.3" ]' \
    'set -g allow-passthrough on'
set -g extended-keys on

set -sg escape-time 10
set -g focus-events on
set -g mouse on
set -g history-limit 100000
set -g set-clipboard on

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
